from matrix import Matrix

matrix = Matrix([])
matrix.read_matrix_from_file('matr2.txt')
matrix.output()
print(f'Размер матрицы: {matrix.size}')
maxmin = matrix.maxmin()
minmax = matrix.minmax()
print(f'Максимин: {maxmin}\nМинимакс: {minmax}')
print("Седловой точки нет") if minmax!=maxmin else print ("Седловая точка есть")
#matrix.write_matrix_to_file('out.txt')
strictly =  matrix.strictly_dominated_strategy()
weakly = matrix.weakly_dominated_strategy()
print(f"Строго доминируемые для игрока А: {strictly[0]}\nСтрого доминируемые для игрока B: {strictly[1]}")
print(f"Слабо доминируемые для игрока А: {weakly[0]}\nСлабо доминируемые для игрока B: {weakly[1]}")
